### ISSUE TITLE
Translate Text Context Menu - reappears after being disabled

### ISSUE THREAD

**Issue by displayerror** [Teh-Lemon/Lemon-X-Chrome-Extension#2]
Hello,
The Translate Text context menu doesn't stay disabled.
On browser restart, the Translate Text menu will appear again!
Okay, thanks!

**Comment by Teh-Lemon** [comment]
Thanks for reporting.
I've uploaded a new version to the Web Store which seems to fix it. Chrome should auto-update at some point in the next few days. Let me know if you still have problems.

I've also added more language options including Auto-Detect if that was your reason for disabling it.

**Comment by displayerror** [comment]
The new auto detect is awesome! I only had the context menu disabled as I was trouble shooting the extension - that's when I noticed that it wouldn't stay disabled.

Some images were failing to enlarge. It seemed that a handful of images wouldn't load or they'd show as missing (seems it was only links from mobile.twitter.com that were affected).
But since the extension update everything is working wonderfully :D
Thank you!!
