### ISSUE TITLE
No longer saving as jpg

### ISSUE THREAD

**Issue by displayerror** [Teh-Lemon/Lemon-X-Chrome-Extension#3]
Hi!
Not sure if this is a problem with my Vivaldi setup but Twitter images have gone back to saving like they did prior, e.g.
EiTaz9LWsAEMf18.jfif

I wonder if this can be solved?
Okay thanks you!

**Comment by Teh-Lemon** [comment]
Most likely a Windows 10 issue. Search Google for "jfif fix".

**Comment by displayerror** [comment]
Yes! That fixed it! I had no idea content type could affect it, thank you!
